### ISSUE TITLE
make error: db.h: No such file or directory

### ISSUE THREAD

**Issue by ksonbol** [hku-systems/apus#4]
Following the steps described, the make step fails with the following error:

Building file: ../src/db/db-interface.c
Invoking: GCC C Compiler
gcc -fPIC -rdynamic -std=gnu11 -DDEBUG=0 -I"/home/karim/code/apus/APUS/RDMA/target/../.local/include" -O0 -g3 -Wall -c -o "src/db/db-interface.o" "../src/db/db-interface.c"
../src/db/db-interface.c:8:10: fatal error: db.h: No such file or directory
 #include <db.h>
          ^~~~~~
compilation terminated.
src/db/subdir.mk:11: recipe for target 'src/db/db-interface.o' failed
make: *** [src/db/db-interface.o] Error 1

**Comment by hemingcui** [comment]
Hi Cheng,
    Please take a look and refine the readme (most likely it is because
some environment var is not set correctly).

**Comment by wnagchenghku** [comment]
Bug fixed. Closing this issue.
