### ISSUE TITLE
APUS leader election incomplete?

### ISSUE THREAD

**Issue by janskrz** [hku-systems/apus#5]
Hello,

I am interested in your leader election and I am trying  to figure out how you implemented it as
described in your  paper (https://core.ac.uk/download/pdf/95561552.pdf). 

As far as I understand, the implementation is in your leader-election-testing branch (dare_server.c).
However, I think that it is incomplete because:
  - dare_sever.c: poll_vote_count(), which seems to be important(?), is never called
  - trying to run the code in this branch causes segmentation faults, e.g.,
     because data.ctr_data is never initialized before accessing it in dare_server.c: init_sever_data()

Is there some working version accessible somewhere else, or did I understand something wrong
so far?

Thanks,

Jan

**Comment by hemingcui** [comment]
Dear Jan,
    Thanks for your interests about our work. My students Cheng/Xusheng
will work with you to resolve the issue.

**Comment by wnagchenghku** [comment]
@janskrz Dear Jan, I'll look into it and reply to you.

**Comment by wnagchenghku** [comment]
Bug fixed. Closing this issue.

**Comment by wnagchenghku** [comment]
Bug fixed. Closing this issue.
